// <auto-generated />
using System;
using Maui.CommandPattern.EntityLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maui.CommandPattern.EntityLibrary.Migrations
{
    [DbContext(typeof(CommandPatternContext))]
    [Migration("20240102180204_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Maui.CommandPattern.EntityLibrary.Models.MtgCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MtgSetId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MtgSetId");

                    b.ToTable("MtgCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "None",
                            Description = "Black Lotus",
                            IsActive = true,
                            MtgSetId = 1,
                            Name = "Black Lotus",
                            Type = "Artifact"
                        },
                        new
                        {
                            Id = 2,
                            Color = "None",
                            Description = "Black Lotus",
                            IsActive = true,
                            MtgSetId = 2,
                            Name = "Black Lotus",
                            Type = "Artifact"
                        });
                });

            modelBuilder.Entity("Maui.CommandPattern.EntityLibrary.Models.MtgSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MtgSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alpha",
                            IsActive = true,
                            Name = "Alpha",
                            ReleaseYear = 1993
                        },
                        new
                        {
                            Id = 2,
                            Description = "Beta",
                            IsActive = true,
                            Name = "Beta",
                            ReleaseYear = 1993
                        });
                });

            modelBuilder.Entity("Maui.CommandPattern.EntityLibrary.Models.MtgCard", b =>
                {
                    b.HasOne("Maui.CommandPattern.EntityLibrary.Models.MtgSet", "MtgSet")
                        .WithMany()
                        .HasForeignKey("MtgSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MtgSet");
                });
#pragma warning restore 612, 618
        }
    }
}
